version: '3'

services:
  database-mysql:
    container_name: database-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '24j89thugrw3hug4'
      TZ: Asia/Seoul
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always
    command: redis-server /usr/local/conf/redis.conf
